title: doodle article
description: doodle articles are documented ideas by Daniel Blake.
creator: Daniel Blake
email: dmblakedesign@gmail.com

baseurl: http://danielblake.design/grouped-svg-sprite/
url: http://danielblake.design/grouped-svg-sprite/

kramdown:
    auto_ids: false
    syntax_highlighter: rouge

port: 4001
